### PR TITLE
feat(compiler): support expression sequences

### LINKED ISSUE #59: Support expression sequences
**Describe the bug**
When combining multiple OCaml expressions with `( expr1 ; expr2 )` or `begin expr1 ; expr2 end`, the resulting Erlang code is "flattened" and can have different result than expected or not compile at all.

**To Reproduce**
1. Create a file `main.ml` containing
```ocaml
let print thing = Io.format "~0tp~n" [ thing ]

let main _ =
  print
    ( print "hej" ;
      true )
```
or
```ocaml
let print thing = Io.format "~0tp~n" [ thing ]

let main _ =
  print
    begin
      print "hej" ;
      true
    end
```
2. Run command `caramel compile main.ml && escript main.erl`
3. See error:
```
main.erl:10: function print/2 undefined
```

This happens because of this incorrect generated Erlang code:
```erlang
% Source code generated with Caramel.
-module(main).

-export([main/1]).
-export([print/1]).

-spec print(_) -> ok.
print(Thing) -> io:format(<<"~0tp~n">>, [Thing | []]).

-spec main(_) -> ok.
main(_) -> print(print(<<"hej">>),
true).
```

**Expected behavior**
Erlang gets generated with:
```erlang
-spec main(_) -> ok.
main(_) -> print(begin print(<<"hej">>), true end).
```

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - Caramel version 0.1
 - Erlang version 23.2.2

### PR DESCRIPTION
**Pull request by michallepicki**
OCaml represents expression sequences as a `(this, next)` expression tuple, where there is no difference in representation of `(a ; b ; c)` vs `(a ; (b ; c))`. So we're translating this representation to a simpler `Expr_seq expr list` in the Erlang AST.
When the expression sequence is present directly inside an Erlang function case definition, the expresison sequence doesn't need to be wrapped in a `begin end` block when pretty printing.

closes #59

Also, compile nested let expressions to expression sequences (relates to #68 ). This is a work in progress - will require generating unique names for variables to avoid scoping issues in Erlang.

### CODE REVIEW

**Comment by michallepicki** [comment]
@ostera I think this works pretty well now! Erlang doesn't need the `begin/end` wrappers when the sequence is directly the body of a function. Do you want me to handle that special case somewhere or are we fine with those additional `begin/end` in function definitions?

**Comment by michallepicki** [comment]
@ostera I went ahead and implemented the change mentioned above. I think this is ready for review now!

**Comment by michallepicki** [comment]
This doesn't add support for parsing `begin/end` expression sequences in the `erlang` library, if it needs such feature, I am not familiar with that part of the codebase yet

**Review by ostera — APPROVED** [review]
Don't worry about the Erlang parser, we're bound to rewrite it anyways. 

This looks awesome 🚀

**Pull request merged**
