### PR TITLE
fix: Support OCaml style floating point syntax without trailing numbers after dot

### LINKED ISSUE #55: Support OCaml style floating point syntax without trailing numbers after dot
Currently this Caramel code compiles:
```
let main _ =
  42.
```

to this Erlang:
```
% Source code generated with Caramel.
-module(main).

-export([main/1]).

-spec main(_) -> float().
main(_) -> 42..
```

Erlang compilation fails with:
```
main.erl:6: syntax error before: '..'
```

This should either:
a) compile to `42.0` in Erlang
b) or print a helpful error when compiling Caramel

Caramel 0.1, Erlang 23.2.2

### PR DESCRIPTION
**Pull request by michallepicki**
closes #55

(not sure if changing the `erl_printer` is the correct fix so I'm happy to change if it's not)

### CODE REVIEW

**Comment by michallepicki** [comment]
Hmm I think this adds a 0 when it's not necessary as well. I'll fix it sometime but the question whether this is the correct place to fix it is still valid :)

**Comment by michallepicki** [comment]
Alternatively I could fix this [here](https://github.com/AbstractMachinesLab/caramel/blob/main/caramel/compiler/ocaml_to_erlang/fun.ml#L14) I think ?

**Comment by ostera** [comment]
@michallepicki yes! the second place feels a lot cleaner since its where all the OCaml->Erlang specific conversions are made. The printer should just assume the Erlang AST is valid.

Additionally, we could add a `Erlang.Ast_helpers.Const.float_of_string` function to do this parsing.

**Comment by michallepicki** [comment]
@ostera There's this helper already: https://github.com/AbstractMachinesLab/caramel/blob/main/erlang/src/erl_ast_helper.ml#L54 - should I modify it instead of adding a new function? It is already being called in the Fun module linked before ( https://github.com/AbstractMachinesLab/caramel/blob/main/caramel/compiler/ocaml_to_erlang/fun.ml#L14 )

**Comment by ostera** [comment]
@michallepicki yup! I think we can use that one as well.

One last alternative would be to start implementing the AST invariants module to return an error if the float's are wrong.

Like, the OCaml_to_Erlang module should be responsible of formatting the floats right, the AST modules should help you verify that it is indeed right.

**Comment by michallepicki** [comment]
@ostera I cannot request a review on the PR but it should be ready to go once CI passes. I added a small test for this kind of float literals.

**Review by ostera — APPROVED** [review]
LGTM! :rocket:

**Pull request merged**
