### PR TITLE
feat(compiler): add basic math operators for integers and floats

### PR DESCRIPTION
**Pull request by michallepicki**

### CODE REVIEW

**Comment by michallepicki** [comment]
Does `escript` not work on MacOs on CI? I can remove the file execution part, just testing `.erl` output is good enough I think.

**Comment by ostera** [comment]
@michallepicki we should make Erlang a CI dependency as well so we can test a few of these things, but right now it is not installed.

Thanks for adding this feature btw! 🙌🏽

**Comment by michallepicki** [comment]
@ostera No problem! So should I remove it for now or would you like to merge as is and make sure to install Erlang on CI sometime later? I am not familiar with the right way to setup erlang on MacOS myself.

**Comment by ostera** [comment]
For now we can leave it out, and we'll get back to this later.

**Review by ostera — APPROVED** [review]
✅

**Pull request merged**
