### PR TITLE
fix(compiler): disable automatic uncurrying

### LINKED ISSUE #44: Function using Io.format compiles to wrong erlang
**Describe the bug**
A simple function that taking no arguments in Caramel, that only runs `Io.format`, compiles to invalid erlang that says it is taking two arguments, which erlang/OTP cannot compile.

**To Reproduce**
```
$ caramelc --version
0.0.14+git-27bc02d
$ cat sweetness.ml 
let text () = "Hello, world!"

let hello () = Io.format (text ())
$ caramelc compile sweetness.ml
Compiling sweetness.erl OK
$ cat sweetness.erl 
% Source code generated with Caramel.
-module(sweetness).

-export([hello/2]).
-export([text/0]).

-spec text() -> binary().
text() -> <<"Hello, world!">>.

-spec hello(ok, list(any())) -> ok.
hello() -> io:format(text()).


$ erl
Erlang/OTP 23 [erts-11.1.6] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]

Eshell V11.1.6  (abort with ^G)
1> c(sweetness).
sweetness.erl:4: function hello/2 undefined
sweetness.erl:10: spec for undefined function hello/2
sweetness.erl:11: Warning: function hello/0 is unused
error
```

**Expected behaviour**
`.erl` gets created with
```
-export([hello/0]).

-spec hello() -> ok.
```

### PR DESCRIPTION
**Pull request by nicobao**
Closes #44 
I am not sure exactly what is expected. This is what I am working on at the moment.

### CODE REVIEW

**Comment by michallepicki** [comment]
I think (I may be wrong) because function body code generation and typespec generation are currently separate, the next thing that will be needed here, is returning an anonymous function from function application [in function application translation](https://github.com/AbstractMachinesLab/caramel/blob/main/caramel/compiler/ocaml_to_erlang/fun.ml#L247) when there are less arguments provided than the function expects. To see how many arguments a function expects we can use `Uncurry.uncurry_tarrow`, like [here](https://github.com/AbstractMachinesLab/caramel/blob/5f77e1db48146ecb69c7ebad72c40c89106b79b6/caramel/compiler/ocaml_to_erlang/fun.ml#L172). I hope this makes sense?

**Comment by michallepicki** [comment]
So I think what I'm proposing is to keep the uncurrying, but do a little bit of work detecting when a single anonymous function wrapper is needed instead. What do you think about it @nicobao @ostera ? Do you think it could work?

**Comment by nicobao** [comment]
Hi,
I look at it this evening or tomorrow evening and let you know. I have a
problem with my computer I need to reinstall it...
I read your previous message and I think it makes sense, however I'd need
to continue diving into the source code to really understand it.
I was starting adding print here and there to understand what's going on,
because atm I'm a little lost, and I haven't put enough time and energy to
get it through as of now.
That being said - if you feel like doing it yourself right now, feel free
to edit that branch directly (if you can) or send another PR. I have no
problem with it!

To be clear, as of now my patch doesn't solve anything... :/ Could you
provide examples as to what you expect the Erlang compilation to look like?


Le mar. 30 mars 2021 à 18:55, Michał Łępicki ***@***.***> a
écrit :

**Comment by michallepicki** [comment]
I looked into this angle, it might work because the information we would need is in the typedtree, but with the current data structures we lose the arity information for function references that are just local identifiers [here](https://github.com/AbstractMachinesLab/caramel/blob/main/caramel/compiler/ocaml_to_erlang/fun.ml#L208). It would be nice to carry over additional type information (in this situation, the arity) for those identifiers. I am not sure if this is something that would live in the Erlang AST or it would be an additional accumulator in `mk_expression`

**Comment by michallepicki** [comment]
And in addition to that we would need to know when other expressions are actually functions as well, and know their arity, e.g. we would know how many arguments a partially applied `Expr_apply` needs as well when resolving the next application... It would be messy and almost begs for an intermediate format between the typedtree and the erlang AST but I think it's possible

**Comment by ostera** [comment]
Hi! 👋🏽  since I'm currently not working on and have no plans to continue working on this version of the compiler, I'll close this PR. Thanks a lot for your contribution 🙏🏽

**Pull request closed without merging**
